// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.clearResetTokenStmt, err = db.PrepareContext(ctx, clearResetToken); err != nil {
		return nil, fmt.Errorf("error preparing query ClearResetToken: %w", err)
	}
	if q.createContactMessageStmt, err = db.PrepareContext(ctx, createContactMessage); err != nil {
		return nil, fmt.Errorf("error preparing query CreateContactMessage: %w", err)
	}
	if q.createCustomerStmt, err = db.PrepareContext(ctx, createCustomer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCustomer: %w", err)
	}
	if q.createInstallmentStmt, err = db.PrepareContext(ctx, createInstallment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateInstallment: %w", err)
	}
	if q.createLoanStmt, err = db.PrepareContext(ctx, createLoan); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLoan: %w", err)
	}
	if q.createLoanProductStmt, err = db.PrepareContext(ctx, createLoanProduct); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLoanProduct: %w", err)
	}
	if q.createPaymentStmt, err = db.PrepareContext(ctx, createPayment); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePayment: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.emailExistsStmt, err = db.PrepareContext(ctx, emailExists); err != nil {
		return nil, fmt.Errorf("error preparing query EmailExists: %w", err)
	}
	if q.getCustomerByIDStmt, err = db.PrepareContext(ctx, getCustomerByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetCustomerByID: %w", err)
	}
	if q.getInstallmentsByLoanStmt, err = db.PrepareContext(ctx, getInstallmentsByLoan); err != nil {
		return nil, fmt.Errorf("error preparing query GetInstallmentsByLoan: %w", err)
	}
	if q.getLoanByIDStmt, err = db.PrepareContext(ctx, getLoanByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetLoanByID: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByPhoneStmt, err = db.PrepareContext(ctx, getUserByPhone); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByPhone: %w", err)
	}
	if q.getUserByResetTokenStmt, err = db.PrepareContext(ctx, getUserByResetToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByResetToken: %w", err)
	}
	if q.listCustomersStmt, err = db.PrepareContext(ctx, listCustomers); err != nil {
		return nil, fmt.Errorf("error preparing query ListCustomers: %w", err)
	}
	if q.listLoanProductsStmt, err = db.PrepareContext(ctx, listLoanProducts); err != nil {
		return nil, fmt.Errorf("error preparing query ListLoanProducts: %w", err)
	}
	if q.listLoansStmt, err = db.PrepareContext(ctx, listLoans); err != nil {
		return nil, fmt.Errorf("error preparing query ListLoans: %w", err)
	}
	if q.phoneExistsStmt, err = db.PrepareContext(ctx, phoneExists); err != nil {
		return nil, fmt.Errorf("error preparing query PhoneExists: %w", err)
	}
	if q.setResetTokenStmt, err = db.PrepareContext(ctx, setResetToken); err != nil {
		return nil, fmt.Errorf("error preparing query SetResetToken: %w", err)
	}
	if q.updateLastLoginStmt, err = db.PrepareContext(ctx, updateLastLogin); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateLastLogin: %w", err)
	}
	if q.updateLoanPaidAmountStmt, err = db.PrepareContext(ctx, updateLoanPaidAmount); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateLoanPaidAmount: %w", err)
	}
	if q.updateLoanStatusStmt, err = db.PrepareContext(ctx, updateLoanStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateLoanStatus: %w", err)
	}
	if q.updatePasswordStmt, err = db.PrepareContext(ctx, updatePassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePassword: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.clearResetTokenStmt != nil {
		if cerr := q.clearResetTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing clearResetTokenStmt: %w", cerr)
		}
	}
	if q.createContactMessageStmt != nil {
		if cerr := q.createContactMessageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createContactMessageStmt: %w", cerr)
		}
	}
	if q.createCustomerStmt != nil {
		if cerr := q.createCustomerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCustomerStmt: %w", cerr)
		}
	}
	if q.createInstallmentStmt != nil {
		if cerr := q.createInstallmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createInstallmentStmt: %w", cerr)
		}
	}
	if q.createLoanStmt != nil {
		if cerr := q.createLoanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLoanStmt: %w", cerr)
		}
	}
	if q.createLoanProductStmt != nil {
		if cerr := q.createLoanProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLoanProductStmt: %w", cerr)
		}
	}
	if q.createPaymentStmt != nil {
		if cerr := q.createPaymentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPaymentStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.emailExistsStmt != nil {
		if cerr := q.emailExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing emailExistsStmt: %w", cerr)
		}
	}
	if q.getCustomerByIDStmt != nil {
		if cerr := q.getCustomerByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCustomerByIDStmt: %w", cerr)
		}
	}
	if q.getInstallmentsByLoanStmt != nil {
		if cerr := q.getInstallmentsByLoanStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getInstallmentsByLoanStmt: %w", cerr)
		}
	}
	if q.getLoanByIDStmt != nil {
		if cerr := q.getLoanByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLoanByIDStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByPhoneStmt != nil {
		if cerr := q.getUserByPhoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByPhoneStmt: %w", cerr)
		}
	}
	if q.getUserByResetTokenStmt != nil {
		if cerr := q.getUserByResetTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByResetTokenStmt: %w", cerr)
		}
	}
	if q.listCustomersStmt != nil {
		if cerr := q.listCustomersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCustomersStmt: %w", cerr)
		}
	}
	if q.listLoanProductsStmt != nil {
		if cerr := q.listLoanProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLoanProductsStmt: %w", cerr)
		}
	}
	if q.listLoansStmt != nil {
		if cerr := q.listLoansStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLoansStmt: %w", cerr)
		}
	}
	if q.phoneExistsStmt != nil {
		if cerr := q.phoneExistsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing phoneExistsStmt: %w", cerr)
		}
	}
	if q.setResetTokenStmt != nil {
		if cerr := q.setResetTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setResetTokenStmt: %w", cerr)
		}
	}
	if q.updateLastLoginStmt != nil {
		if cerr := q.updateLastLoginStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateLastLoginStmt: %w", cerr)
		}
	}
	if q.updateLoanPaidAmountStmt != nil {
		if cerr := q.updateLoanPaidAmountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateLoanPaidAmountStmt: %w", cerr)
		}
	}
	if q.updateLoanStatusStmt != nil {
		if cerr := q.updateLoanStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateLoanStatusStmt: %w", cerr)
		}
	}
	if q.updatePasswordStmt != nil {
		if cerr := q.updatePasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePasswordStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	clearResetTokenStmt       *sql.Stmt
	createContactMessageStmt  *sql.Stmt
	createCustomerStmt        *sql.Stmt
	createInstallmentStmt     *sql.Stmt
	createLoanStmt            *sql.Stmt
	createLoanProductStmt     *sql.Stmt
	createPaymentStmt         *sql.Stmt
	createUserStmt            *sql.Stmt
	emailExistsStmt           *sql.Stmt
	getCustomerByIDStmt       *sql.Stmt
	getInstallmentsByLoanStmt *sql.Stmt
	getLoanByIDStmt           *sql.Stmt
	getUserByEmailStmt        *sql.Stmt
	getUserByIDStmt           *sql.Stmt
	getUserByPhoneStmt        *sql.Stmt
	getUserByResetTokenStmt   *sql.Stmt
	listCustomersStmt         *sql.Stmt
	listLoanProductsStmt      *sql.Stmt
	listLoansStmt             *sql.Stmt
	phoneExistsStmt           *sql.Stmt
	setResetTokenStmt         *sql.Stmt
	updateLastLoginStmt       *sql.Stmt
	updateLoanPaidAmountStmt  *sql.Stmt
	updateLoanStatusStmt      *sql.Stmt
	updatePasswordStmt        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		clearResetTokenStmt:       q.clearResetTokenStmt,
		createContactMessageStmt:  q.createContactMessageStmt,
		createCustomerStmt:        q.createCustomerStmt,
		createInstallmentStmt:     q.createInstallmentStmt,
		createLoanStmt:            q.createLoanStmt,
		createLoanProductStmt:     q.createLoanProductStmt,
		createPaymentStmt:         q.createPaymentStmt,
		createUserStmt:            q.createUserStmt,
		emailExistsStmt:           q.emailExistsStmt,
		getCustomerByIDStmt:       q.getCustomerByIDStmt,
		getInstallmentsByLoanStmt: q.getInstallmentsByLoanStmt,
		getLoanByIDStmt:           q.getLoanByIDStmt,
		getUserByEmailStmt:        q.getUserByEmailStmt,
		getUserByIDStmt:           q.getUserByIDStmt,
		getUserByPhoneStmt:        q.getUserByPhoneStmt,
		getUserByResetTokenStmt:   q.getUserByResetTokenStmt,
		listCustomersStmt:         q.listCustomersStmt,
		listLoanProductsStmt:      q.listLoanProductsStmt,
		listLoansStmt:             q.listLoansStmt,
		phoneExistsStmt:           q.phoneExistsStmt,
		setResetTokenStmt:         q.setResetTokenStmt,
		updateLastLoginStmt:       q.updateLastLoginStmt,
		updateLoanPaidAmountStmt:  q.updateLoanPaidAmountStmt,
		updateLoanStatusStmt:      q.updateLoanStatusStmt,
		updatePasswordStmt:        q.updatePasswordStmt,
	}
}
