// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type LoansStatus string

const (
	LoansStatusPending   LoansStatus = "pending"
	LoansStatusApproved  LoansStatus = "approved"
	LoansStatusRejected  LoansStatus = "rejected"
	LoansStatusActive    LoansStatus = "active"
	LoansStatusCompleted LoansStatus = "completed"
)

func (e *LoansStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoansStatus(s)
	case string:
		*e = LoansStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LoansStatus: %T", src)
	}
	return nil
}

type NullLoansStatus struct {
	LoansStatus LoansStatus `json:"loans_status"`
	Valid       bool        `json:"valid"` // Valid is true if LoansStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoansStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LoansStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoansStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoansStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoansStatus), nil
}

type UsersRole string

const (
	UsersRoleUser  UsersRole = "user"
	UsersRoleAdmin UsersRole = "admin"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type ContactMessage struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Message   string       `json:"message"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Customer struct {
	ID         int64          `json:"id"`
	FullName   sql.NullString `json:"full_name"`
	Phone      sql.NullString `json:"phone"`
	NationalID sql.NullString `json:"national_id"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Loan struct {
	ID            int64           `json:"id"`
	CustomerID    sql.NullInt64   `json:"customer_id"`
	LoanProductID sql.NullInt64   `json:"loan_product_id"`
	Principal     sql.NullString  `json:"principal"`
	Interest      sql.NullString  `json:"interest"`
	TotalAmount   sql.NullString  `json:"total_amount"`
	PaidAmount    sql.NullString  `json:"paid_amount"`
	Status        NullLoansStatus `json:"status"`
	DisbursedAt   sql.NullTime    `json:"disbursed_at"`
	CreatedAt     sql.NullTime    `json:"created_at"`
}

type LoanInstallment struct {
	ID      int64          `json:"id"`
	LoanID  sql.NullInt64  `json:"loan_id"`
	DueDate sql.NullTime   `json:"due_date"`
	Amount  sql.NullString `json:"amount"`
	Paid    sql.NullBool   `json:"paid"`
}

type LoanPayment struct {
	ID        int64          `json:"id"`
	LoanID    sql.NullInt64  `json:"loan_id"`
	Amount    sql.NullString `json:"amount"`
	Method    sql.NullString `json:"method"`
	Reference sql.NullString `json:"reference"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type LoanProduct struct {
	ID           int64          `json:"id"`
	Name         sql.NullString `json:"name"`
	InterestRate sql.NullString `json:"interest_rate"`
	DurationDays sql.NullInt32  `json:"duration_days"`
	PenaltyRate  sql.NullString `json:"penalty_rate"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type User struct {
	ID               int64          `json:"id"`
	FullName         string         `json:"full_name"`
	Email            string         `json:"email"`
	Phone            string         `json:"phone"`
	PasswordHash     string         `json:"password_hash"`
	Role             UsersRole      `json:"role"`
	IsVerified       bool           `json:"is_verified"`
	ResetToken       sql.NullString `json:"reset_token"`
	ResetTokenExpiry sql.NullTime   `json:"reset_token_expiry"`
	LastLogin        sql.NullTime   `json:"last_login"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}
