// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const clearResetToken = `-- name: ClearResetToken :exec
UPDATE users
SET reset_token = NULL,
    reset_token_expiry = NULL,
    updated_at = NOW()
WHERE id = ?
`

func (q *Queries) ClearResetToken(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.clearResetTokenStmt, clearResetToken, id)
	return err
}

const createCustomer = `-- name: CreateCustomer :execresult
INSERT INTO customers (full_name, phone, national_id)
VALUES (?, ?, ?)
`

type CreateCustomerParams struct {
	FullName   sql.NullString `json:"full_name"`
	Phone      sql.NullString `json:"phone"`
	NationalID sql.NullString `json:"national_id"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (sql.Result, error) {
	return q.exec(ctx, q.createCustomerStmt, createCustomer, arg.FullName, arg.Phone, arg.NationalID)
}

const createInstallment = `-- name: CreateInstallment :exec
INSERT INTO loan_installments (loan_id, due_date, amount)
VALUES (?, ?, ?)
`

type CreateInstallmentParams struct {
	LoanID  sql.NullInt64  `json:"loan_id"`
	DueDate sql.NullTime   `json:"due_date"`
	Amount  sql.NullString `json:"amount"`
}

func (q *Queries) CreateInstallment(ctx context.Context, arg CreateInstallmentParams) error {
	_, err := q.exec(ctx, q.createInstallmentStmt, createInstallment, arg.LoanID, arg.DueDate, arg.Amount)
	return err
}

const createLoan = `-- name: CreateLoan :execresult
INSERT INTO loans (
 customer_id, loan_product_id, principal, interest, total_amount, status
) VALUES (?, ?, ?, ?, ?, 'pending')
`

type CreateLoanParams struct {
	CustomerID    sql.NullInt64  `json:"customer_id"`
	LoanProductID sql.NullInt64  `json:"loan_product_id"`
	Principal     sql.NullString `json:"principal"`
	Interest      sql.NullString `json:"interest"`
	TotalAmount   sql.NullString `json:"total_amount"`
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (sql.Result, error) {
	return q.exec(ctx, q.createLoanStmt, createLoan,
		arg.CustomerID,
		arg.LoanProductID,
		arg.Principal,
		arg.Interest,
		arg.TotalAmount,
	)
}

const createLoanProduct = `-- name: CreateLoanProduct :execresult
INSERT INTO loan_products (name, interest_rate, duration_days, penalty_rate)
VALUES (?, ?, ?, ?)
`

type CreateLoanProductParams struct {
	Name         sql.NullString `json:"name"`
	InterestRate sql.NullString `json:"interest_rate"`
	DurationDays sql.NullInt32  `json:"duration_days"`
	PenaltyRate  sql.NullString `json:"penalty_rate"`
}

func (q *Queries) CreateLoanProduct(ctx context.Context, arg CreateLoanProductParams) (sql.Result, error) {
	return q.exec(ctx, q.createLoanProductStmt, createLoanProduct,
		arg.Name,
		arg.InterestRate,
		arg.DurationDays,
		arg.PenaltyRate,
	)
}

const createPayment = `-- name: CreatePayment :execresult
INSERT INTO loan_payments (loan_id, amount, method, reference)
VALUES (?, ?, ?, ?)
`

type CreatePaymentParams struct {
	LoanID    sql.NullInt64  `json:"loan_id"`
	Amount    sql.NullString `json:"amount"`
	Method    sql.NullString `json:"method"`
	Reference sql.NullString `json:"reference"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (sql.Result, error) {
	return q.exec(ctx, q.createPaymentStmt, createPayment,
		arg.LoanID,
		arg.Amount,
		arg.Method,
		arg.Reference,
	)
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (full_name, email, phone, password_hash, role)
VALUES (?, ?, ?, ?, 'user')
`

type CreateUserParams struct {
	FullName     string `json:"full_name"`
	Email        string `json:"email"`
	Phone        string `json:"phone"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.exec(ctx, q.createUserStmt, createUser,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
	)
}

const emailExists = `-- name: EmailExists :one
SELECT COUNT(*) FROM users WHERE email = ?
`

func (q *Queries) EmailExists(ctx context.Context, email string) (int64, error) {
	row := q.queryRow(ctx, q.emailExistsStmt, emailExists, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, full_name, phone, national_id, created_at FROM customers WHERE id = ? LIMIT 1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id int64) (Customer, error) {
	row := q.queryRow(ctx, q.getCustomerByIDStmt, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.NationalID,
		&i.CreatedAt,
	)
	return i, err
}

const getInstallmentsByLoan = `-- name: GetInstallmentsByLoan :many
SELECT id, loan_id, due_date, amount, paid FROM loan_installments WHERE loan_id = ?
`

func (q *Queries) GetInstallmentsByLoan(ctx context.Context, loanID sql.NullInt64) ([]LoanInstallment, error) {
	rows, err := q.query(ctx, q.getInstallmentsByLoanStmt, getInstallmentsByLoan, loanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanInstallment
	for rows.Next() {
		var i LoanInstallment
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.DueDate,
			&i.Amount,
			&i.Paid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLoanByID = `-- name: GetLoanByID :one
SELECT id, customer_id, loan_product_id, principal, interest, total_amount, paid_amount, status, disbursed_at, created_at FROM loans WHERE id = ? LIMIT 1
`

func (q *Queries) GetLoanByID(ctx context.Context, id int64) (Loan, error) {
	row := q.queryRow(ctx, q.getLoanByIDStmt, getLoanByID, id)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.LoanProductID,
		&i.Principal,
		&i.Interest,
		&i.TotalAmount,
		&i.PaidAmount,
		&i.Status,
		&i.DisbursedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, phone, password_hash, role, is_verified, reset_token, reset_token_expiry, last_login, created_at, updated_at FROM users
WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.IsVerified,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, email, phone, password_hash, role, is_verified, reset_token, reset_token_expiry, last_login, created_at, updated_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.IsVerified,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, full_name, email, phone, password_hash, role, is_verified, reset_token, reset_token_expiry, last_login, created_at, updated_at FROM users
WHERE phone = ? LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.queryRow(ctx, q.getUserByPhoneStmt, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.IsVerified,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByResetToken = `-- name: GetUserByResetToken :one
SELECT id, full_name, email, phone, password_hash, role, is_verified, reset_token, reset_token_expiry, last_login, created_at, updated_at FROM users
WHERE reset_token = ?
  AND reset_token_expiry > NOW()
LIMIT 1
`

func (q *Queries) GetUserByResetToken(ctx context.Context, resetToken sql.NullString) (User, error) {
	row := q.queryRow(ctx, q.getUserByResetTokenStmt, getUserByResetToken, resetToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.IsVerified,
		&i.ResetToken,
		&i.ResetTokenExpiry,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, full_name, phone, national_id, created_at FROM customers ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.query(ctx, q.listCustomersStmt, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Phone,
			&i.NationalID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoanProducts = `-- name: ListLoanProducts :many
SELECT id, name, interest_rate, duration_days, penalty_rate, created_at FROM loan_products
`

func (q *Queries) ListLoanProducts(ctx context.Context) ([]LoanProduct, error) {
	rows, err := q.query(ctx, q.listLoanProductsStmt, listLoanProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanProduct
	for rows.Next() {
		var i LoanProduct
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InterestRate,
			&i.DurationDays,
			&i.PenaltyRate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoans = `-- name: ListLoans :many
SELECT id, customer_id, loan_product_id, principal, interest, total_amount, paid_amount, status, disbursed_at, created_at FROM loans ORDER BY id DESC LIMIT ? OFFSET ?
`

type ListLoansParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListLoans(ctx context.Context, arg ListLoansParams) ([]Loan, error) {
	rows, err := q.query(ctx, q.listLoansStmt, listLoans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.LoanProductID,
			&i.Principal,
			&i.Interest,
			&i.TotalAmount,
			&i.PaidAmount,
			&i.Status,
			&i.DisbursedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const phoneExists = `-- name: PhoneExists :one
SELECT COUNT(*) FROM users WHERE phone = ?
`

func (q *Queries) PhoneExists(ctx context.Context, phone string) (int64, error) {
	row := q.queryRow(ctx, q.phoneExistsStmt, phoneExists, phone)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setResetToken = `-- name: SetResetToken :exec
UPDATE users
SET reset_token = ?,
    reset_token_expiry = ?,
    updated_at = NOW()
WHERE email = ?
`

type SetResetTokenParams struct {
	ResetToken       sql.NullString `json:"reset_token"`
	ResetTokenExpiry sql.NullTime   `json:"reset_token_expiry"`
	Email            string         `json:"email"`
}

func (q *Queries) SetResetToken(ctx context.Context, arg SetResetTokenParams) error {
	_, err := q.exec(ctx, q.setResetTokenStmt, setResetToken, arg.ResetToken, arg.ResetTokenExpiry, arg.Email)
	return err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login = NOW()
WHERE id = ?
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.updateLastLoginStmt, updateLastLogin, id)
	return err
}

const updateLoanPaidAmount = `-- name: UpdateLoanPaidAmount :exec
UPDATE loans SET paid_amount = paid_amount + ? WHERE id = ?
`

type UpdateLoanPaidAmountParams struct {
	PaidAmount sql.NullString `json:"paid_amount"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateLoanPaidAmount(ctx context.Context, arg UpdateLoanPaidAmountParams) error {
	_, err := q.exec(ctx, q.updateLoanPaidAmountStmt, updateLoanPaidAmount, arg.PaidAmount, arg.ID)
	return err
}

const updateLoanStatus = `-- name: UpdateLoanStatus :exec
UPDATE loans SET status = ? WHERE id = ?
`

type UpdateLoanStatusParams struct {
	Status NullLoansStatus `json:"status"`
	ID     int64           `json:"id"`
}

func (q *Queries) UpdateLoanStatus(ctx context.Context, arg UpdateLoanStatusParams) error {
	_, err := q.exec(ctx, q.updateLoanStatusStmt, updateLoanStatus, arg.Status, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = ?, updated_at = NOW()
WHERE id = ?
`

type UpdatePasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.exec(ctx, q.updatePasswordStmt, updatePassword, arg.PasswordHash, arg.ID)
	return err
}
